CREATE TABLE POKEMON(
       ID_POKEMON INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(15) NOT NULL,
	   MOTE VARCHAR(20),
       VITALIDAD INT NOT NULL,
	   ATAQUE INT NOT NULL,
	   DEFENSA INT NOT NULL,
	   ATAQUE_ESP INT NOT NULL,
	   DEFENSA_ESP INT NOT NULL,
	   VELOCIDAD INT NOT NULL,
	   ESTAMINA INT NOT NULL,
	   NIVEL INT NOT NULL,
	   EXPERIENCIA INT,
       MOVIMIENTOS VARCHAR(15),
	   FERTILIDAD INT DEFAULT 5,
	   TIPO1 VARCHAR(10) NOT NULL,
	   TIPO2 VARCHAR(10),
	   ESTADO VARCHAR(10) DEFAULT 'SIN_ESTADO',
       SPRITE VARCHAR(80)
);

CREATE TABLE ENTRENADOR(
       ID_ENTRENADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(10) NOT NULL,
       POKEDOLLARS INT DEFAULT 500,
       POKEMONS VARCHAR(15),
       POKEMONS_CAJA VARCHAR(4000)
);

CREATE TABLE COMBATE(
       ID_COMBATE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       JUGADOR INT NOT NULL,
       RIVAL INT NOT NULL, 
       GANADOR INT, 
       TURNOS VARCHAR(4000), 
       POKEMON_KO_JUGADOR VARCHAR(15), 
       POKEMON_KO_RIVAL VARCHAR(15), 
	   CONSTRAINT COMBATE_JUGADOR_FK FOREIGN KEY (JUGADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR),
	   CONSTRAINT COMBATE_RIVAL_FK FOREIGN KEY (RIVAL) REFERENCES ENTRENADOR (ID_ENTRENADOR),
	   CONSTRAINT COMBATE_GANADOR_FK FOREIGN KEY (GANADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR)
);
	
CREATE TABLE MOVIMIENTO(
       ID_MOVIMIENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(20) NOT NULL,
       POTENCIA INT,
       TIPO VARCHAR(10),
       ESTADO VARCHAR(10),
       MEJORA INT
);
	   
CREATE TABLE TURNO(
       ID_TURNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NUM_TURNO INT,
       MOVIMIENTO_JUGADOR INT,
       MOVIMIENTO_RIVAL INT,
	   CONSTRAINT TURNO_JUGADOR_FK FOREIGN KEY (MOVIMIENTO_JUGADOR) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
       CONSTRAINT TURNO_RIVAL_FK FOREIGN KEY (MOVIMIENTO_RIVAL) REFERENCES MOVIMIENTO (ID_MOVIMIENTO)
);
	  

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PUNO FUEGO', 'FIRE', 75);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('CASCADA', 'WATER', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('MARTILLAZO', 'WATER', 10);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('TENAZA', 'WATER', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('HIDROBOMBA', 'WATER', 120);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PISTOLA AGUA', 'WATER', 40);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('SURF', 'WATER', 90);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LATIGO CEPA', 'PLANT', 10);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ABSORBER', 'PLANT', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('DANZA PETALO', 'PLANT', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('HOJA AFILADA', 'PLANT', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('MEGAAGOTAR', 'PLANT', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('RAYO SOLAR', 'PLANT', 15);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('CHUPAVIDAS', 'BUG', 80);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PIN MISIL', 'BUG', 25);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('FURIA DRAGON', 'DRAGON', 100);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ONDA TRUENO', 'ELECTRIC', 90);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LENGUETAZO', 'GHOST', 50);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('NEBLINA', 'ICE', 100);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('CONTRAATAQUE', 'FIGHTING', 75);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('DOBLE PATADA', 'FIGHTING', 30);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('MOVIMIENTO SISMICO', 'FIGHTING', 30);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PATADA BAJA', 'FIGHTING', 50);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PATADA GIRO', 'FIGHTING', 60);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PATADA SALTO', 'FIGHTING', 100);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PATADA SALTO ALTA', 'FIGHTING', 130);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('SUMISION', 'FIGHTING', 80);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('AGARRE', 'NORMAL', 55);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ARANAZO', 'NORMAL', 40);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ATADURA', 'NORMAL', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ATAQUE FURIA', 'NORMAL', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ATAQUE RAPIDO', 'NORMAL', 40);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LATIGO', 'NORMAL', 75);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('COME SUENOS', 'PHYCHIC', 100);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PSICOONDA', 'PHYCHIC', 50);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('AVALANCHA', 'ROCK', 75);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LANZARROCAS', 'ROCK', 50);


INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('HUESO PALO', 'GRASS', 65);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('HUESOMERANG', 'GRASS', 50);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('TERREMOTO', 'GRASS', 100);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ATAQUE AEREO', 'FLYING', 140);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('ATAQUE ALA', 'FLYING', 60);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PICO TALADRO', 'FLYING', 80);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PICOTAZO', 'FLYING', 35);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('ASCUAS', 'FIRE', 'QUEMADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('LANZALLAMAS', 'FIRE', 'QUEMADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('GIRO FUEGO', 'FIRE', 'QUEMADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('LLAMARADA', 'FIRE', 'QUEMADO');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('BURBUJA', 'WATER','REDUCIR VELOCIDAD');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('RAYO BURBUJA', 'WATER','REDUCIR VELOCIDAD');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('ESPORAS', 'PLANT', 'DORMIDO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PARALIZADOR', 'PLANT', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PARALIZAR', 'PLANT', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('SOMNIFERO', 'PLANT', 'DORMIDO');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('DOBLE ATAQUE', 'BUG','ENVENENAR');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('DISPARO DEMORA', 'BUG','REDUCIR VELOCIDAD');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PUNO ELECTRICO', 'ELECTRIC', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('IMPACTRUENO', 'ELECTRIC', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('RAYO', 'ELECTRIC', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('TRUENO', 'ELECTRIC', 'PARALIZADO');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('LENGUETAZO', 'GHOST', 'PARALIZADO');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('RAYO CONFUSO', 'GHOST', 'CONFUSION');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PUNO HIELO', 'ICE', 'CONGELA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('RAYO HIELO', 'ICE', 'CONGELA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('VENTISCA', 'ICE', 'CONGELA');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('CONFUSION', 'PHYCHIC', 'CONFUNDE');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PSICORAYO', 'PHYCHIC', 'CONFUNDE');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('HIPNOSIS', 'PHYCHIC', 'DUERME');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('PICOTAZO VENENO', 'POISON', 'ENVENENA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('POLUCION', 'POISON', 'ENVENENA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('RESIDUOS', 'POISON', 'ENVENENA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('GAS VENENOSO', 'POISON', 'ENVENENA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('POLVO VENENOSO', 'POISON', 'ENVENENA');
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO) VALUES('TOXICO', 'POISON', 'ENVENENA');

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('POTENCIAR ATAQUE', 'FIGHTING', 5);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('POTENCIAR DEFENSA', 'NORMAL', 3);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('REFUJIO', 'WATER', 3);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('RAYO AURORA', 'ICE', 2);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('PSIQUICO', 'PSYCHIC', 2);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('AGILIDAD', 'PSYCHIC', 1);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('BARRERA', 'PSYCHIC', 2);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('MEDITACION', 'PSYCHIC', 2);

INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('ACIDO', 'POISON', 2);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA) VALUES('ARMADURA ACIDA', 'POISON', 2);