CREATE TABLE POKEMON(
       ID_POKEMON INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(15) NOT NULL,
	   MOTE VARCHAR(20),
       VITALIDAD INT NOT NULL,
	   ATAQUE INT NOT NULL,
	   DEFENSA INT NOT NULL,
	   ATAQUE_ESP INT NOT NULL,
	   DEFENSA_ESP INT NOT NULL,
	   VELOCIDAD INT NOT NULL,
	   ESTAMINA INT NOT NULL,
	   NIVEL INT NOT NULL,
	   EXPERIENCIA INT,
       MOVIMIENTOS VARCHAR(15),
	   FERTILIDAD INT DEFAULT(5),
	   TIPO1 VARCHAR(10) NOT NULL,
	   TIPO2 VARCHAR(10),
	   ESTADO VARCHAR(10) DEFAULT('SIN_ESTADO'),
       SPRITE VARCHAR(80)
);

CREATE TABLE ENTRENADOR(
       ID_ENTRENADOR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(10) NOT NULL,
       POKEDOLLARS INT DEFAULT 500,
       POKEMONS VARCHAR(15),
       POKEMONS_CAJA VARCHAR(4000)
);

CREATE TABLE COMBATE(
       ID_COMBATE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       JUGADOR INT NOT NULL,
       RIVAL INT NOT NULL, 
       GANADOR INT, 
       TURNOS VARCHAR(4000), 
       POKEMON_KO_JUGADOR VARCHAR(15), 
       POKEMON_KO_RIVAL VARCHAR(15), 
	   CONSTRAINT COMBATE_JUGADOR_FK FOREIGN KEY (JUGADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR),
	   CONSTRAINT COMBATE_RIVAL_FK FOREIGN KEY (RIVAL) REFERENCES ENTRENADOR (ID_ENTRENADOR),
	   CONSTRAINT COMBATE_GANADOR_FK FOREIGN KEY (GANADOR) REFERENCES ENTRENADOR (ID_ENTRENADOR)
);
	
CREATE TABLE MOVIMIENTO(
       ID_MOVIMIENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NOMBRE VARCHAR(20) NOT NULL,
       POTENCIA INT,
       TIPO VARCHAR(10),
       ESTADO VARCHAR(10),
       MEJORA INT,
	   NUM_TURNOS INT
);
	   
CREATE TABLE TURNO(
       ID_TURNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
       NUM_TURNO INT,
       MOVIMIENTO_JUGADOR INT,
       MOVIMIENTO_RIVAL INT,
	   CONSTRAINT TURNO_JUGADOR_FK FOREIGN KEY (MOVIMIENTO_JUGADOR) REFERENCES MOVIMIENTO (ID_MOVIMIENTO),
       CONSTRAINT TURNO_RIVAL_FK FOREIGN KEY (MOVIMIENTO_RIVAL) REFERENCES MOVIMIENTO (ID_MOVIMIENTO)
);
	   
--ENTRENADORES	   
INSERT INTO ENTRENADOR(NOMBRE) VALUES('ANTONIO');
INSERT INTO ENTRENADOR(NOMBRE) VALUES('PERICO');
INSERT INTO ENTRENADOR(NOMBRE) VALUES('ROBERTO');
INSERT INTO ENTRENADOR(NOMBRE) VALUES('KYLIAN'); 

--COMBATES
INSERT INTO COMBATE(JUGADOR, RIVAL, GANADOR) VALUES(1,2,3);
INSERT INTO COMBATE(JUGADOR, RIVAL, GANADOR) VALUES(2,4,1);
INSERT INTO COMBATE(JUGADOR, RIVAL, GANADOR) VALUES(3,4,2);

--TIPOS POSIBLES: STEEL, WATER, BUG, DRAGON, ELECTRIC, GHOST, FIRE, FAIRY, ICE, FIGHTING, NORMAL, GRASS, PSYCHIC, ROCK, DARK, GROUND, POISON, FLYING

--MOVIMIENTOS ATAQUE
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LANZALLAMAS', 'FIRE', 30);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('PISTOLA DE AGUA', 'WATER', 15);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, POTENCIA) VALUES('LATIGO CEPA', 'PLANT', 10);

--MOVIMIENTOS ESTADO
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO, NUM_TURNOS) VALUES('PARALIZAR', 'ELECTRIC', 'PARALIZADO', 3);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO, NUM_TURNOS) VALUES('SOMNIFERO', 'GRASS', 'DORMIDO', 5);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, ESTADO, NUM_TURNOS) VALUES('ASCUAS', 'FIRE', 'QUEMADO', 2);

--MOVIMIENTOS MEJORA
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA, NUM_TURNOS) VALUES('POTENCIAR ATAQUE', 'FIGHTING', 5, 1,);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA, NUM_TURNOS) VALUES('POTENCIAR DEFENSA', 'NORMAL', 3, 2);
INSERT INTO MOVIMIENTO(NOMBRE, TIPO, MEJORA, NUM_TURNOS) VALUES('POTENCIAR ATAQUE_ESP', 'PSYCHIC', 6, 2);

--TURNOS
INSERT INTO TURNO(NUM_TURNO, MOVIMIENTO_JUGADOR, MOVIMIENTO_RIVAL) VALUES(1, 1, 2);
INSERT INTO TURNO(NUM_TURNO, MOVIMIENTO_JUGADOR, MOVIMIENTO_RIVAL) VALUES(1, 2, 3);
INSERT INTO TURNO(NUM_TURNO, MOVIMIENTO_JUGADOR, MOVIMIENTO_RIVAL) VALUES(1, 4, 5);